stages:
  train:
    cmd: python src/main.py --config=params.yaml
    deps:
      - dataset/data_train.csv
      - dataset/data_eval.csv
      - dataset/answer_space.txt
      - src/main.py
    params:
      - base
      - data
      - tokenizer
      - model
      - train
      - metrics
    metrics:
      - metrics/metrics.json:
          cache: false
